-- This migration was generated before the initial table-creation migration and
-- cannot be applied to a fresh shadow database because the target tables do not
-- exist yet. Keep it as a no-op so Prisma can replay migration history cleanly.
